
package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

public class FormMenuPrincipal extends javax.swing.JFrame {
    
    
    public static JDesktopPane jDesktopPaneMenu;
    
    public FormMenuPrincipal() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Inventario - Dulceria");
        
        this.setLayout(null);
        jDesktopPaneMenu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPaneMenu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPaneMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_Nuevo_Usuario = new javax.swing.JMenuItem();
        jMenuItem_Gestionar_Usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Ingresar_Producto = new javax.swing.JMenuItem();
        jMenuItem_Gestion_Productos = new javax.swing.JMenuItem();
        jMenuItem_Actualizar_Stock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_Ingresar_Categoria = new javax.swing.JMenuItem();
        jMenuItem_Gestionar_Categoria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_Registrar_Cliente = new javax.swing.JMenuItem();
        jMenuItem_Gestionar_Cliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_Registrar_Venta = new javax.swing.JMenuItem();
        jMenuItem_Gestionar_Venta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_Reporte_Categorias = new javax.swing.JMenuItem();
        jMenuItem_Reporte_Clientes = new javax.swing.JMenuItem();
        jMenuItem_Reporte_Inventario = new javax.swing.JMenuItem();
        jMenuItem_Reporte_Ventas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_Reporte_Historial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_Cerrar_Sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Usuario");
        jMenu1.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Nuevo_Usuario.setText("Nuevo usuario");
        jMenuItem_Nuevo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Nuevo_UsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Nuevo_Usuario);

        jMenuItem_Gestionar_Usuario.setText("Gestión de usuarios");
        jMenu1.add(jMenuItem_Gestionar_Usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");
        jMenu2.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Ingresar_Producto.setText("Ingresar productos");
        jMenuItem_Ingresar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Ingresar_ProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Ingresar_Producto);

        jMenuItem_Gestion_Productos.setText("Gestión de productos");
        jMenu2.add(jMenuItem_Gestion_Productos);

        jMenuItem_Actualizar_Stock.setText("Actualizar stock");
        jMenu2.add(jMenuItem_Actualizar_Stock);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Categorías");
        jMenu3.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Ingresar_Categoria.setText("Ingresar categoría");
        jMenuItem_Ingresar_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Ingresar_CategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Ingresar_Categoria);

        jMenuItem_Gestionar_Categoria.setText("Gestionar categoría");
        jMenuItem_Gestionar_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Gestionar_CategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Gestionar_Categoria);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Clientes");
        jMenu4.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Registrar_Cliente.setText("Registrar cliente");
        jMenu4.add(jMenuItem_Registrar_Cliente);

        jMenuItem_Gestionar_Cliente.setText("Gestionar cliente");
        jMenuItem_Gestionar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Gestionar_ClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Gestionar_Cliente);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ventas");
        jMenu5.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Registrar_Venta.setText("Registrar venta");
        jMenu5.add(jMenuItem_Registrar_Venta);

        jMenuItem_Gestionar_Venta.setText("Gestionar venta");
        jMenu5.add(jMenuItem_Gestionar_Venta);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Reportes");
        jMenu6.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Reporte_Categorias.setText("Categorías");
        jMenuItem_Reporte_Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Reporte_CategoriasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_Reporte_Categorias);

        jMenuItem_Reporte_Clientes.setText("Clientes");
        jMenuItem_Reporte_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Reporte_ClientesActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_Reporte_Clientes);

        jMenuItem_Reporte_Inventario.setText("Inventario");
        jMenu6.add(jMenuItem_Reporte_Inventario);

        jMenuItem_Reporte_Ventas.setText("Ventas");
        jMenu6.add(jMenuItem_Reporte_Ventas);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Historial");
        jMenu7.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Reporte_Historial.setText("Historial");
        jMenuItem_Reporte_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Reporte_HistorialActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_Reporte_Historial);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Cerrar Sesión");
        jMenu8.setPreferredSize(new java.awt.Dimension(80, 30));

        jMenuItem_Cerrar_Sesion.setText("Cerrar sesión");
        jMenu8.add(jMenuItem_Cerrar_Sesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Nuevo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Nuevo_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Nuevo_UsuarioActionPerformed

    private void jMenuItem_Ingresar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Ingresar_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Ingresar_ProductoActionPerformed

    private void jMenuItem_Gestionar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Gestionar_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Gestionar_ClienteActionPerformed

    private void jMenuItem_Reporte_CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Reporte_CategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Reporte_CategoriasActionPerformed

    private void jMenuItem_Reporte_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Reporte_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Reporte_ClientesActionPerformed

    private void jMenuItem_Reporte_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Reporte_HistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Reporte_HistorialActionPerformed

    private void jMenuItem_Ingresar_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Ingresar_CategoriaActionPerformed
      
        InternalFormCategoria internalFormCategoria = new InternalFormCategoria();
        jDesktopPaneMenu.add(internalFormCategoria);
        internalFormCategoria.setVisible(true);
        
        
    
    }//GEN-LAST:event_jMenuItem_Ingresar_CategoriaActionPerformed

    private void jMenuItem_Gestionar_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Gestionar_CategoriaActionPerformed
        
        InternalFormGestionarCategoria internalFormGestionarCategoria = new InternalFormGestionarCategoria();
        jDesktopPaneMenu.add(internalFormGestionarCategoria);
        internalFormGestionarCategoria.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_Gestionar_CategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Actualizar_Stock;
    private javax.swing.JMenuItem jMenuItem_Cerrar_Sesion;
    private javax.swing.JMenuItem jMenuItem_Gestion_Productos;
    private javax.swing.JMenuItem jMenuItem_Gestionar_Categoria;
    private javax.swing.JMenuItem jMenuItem_Gestionar_Cliente;
    private javax.swing.JMenuItem jMenuItem_Gestionar_Usuario;
    private javax.swing.JMenuItem jMenuItem_Gestionar_Venta;
    private javax.swing.JMenuItem jMenuItem_Ingresar_Categoria;
    private javax.swing.JMenuItem jMenuItem_Ingresar_Producto;
    private javax.swing.JMenuItem jMenuItem_Nuevo_Usuario;
    private javax.swing.JMenuItem jMenuItem_Registrar_Cliente;
    private javax.swing.JMenuItem jMenuItem_Registrar_Venta;
    private javax.swing.JMenuItem jMenuItem_Reporte_Categorias;
    private javax.swing.JMenuItem jMenuItem_Reporte_Clientes;
    private javax.swing.JMenuItem jMenuItem_Reporte_Historial;
    private javax.swing.JMenuItem jMenuItem_Reporte_Inventario;
    private javax.swing.JMenuItem jMenuItem_Reporte_Ventas;
    // End of variables declaration//GEN-END:variables
}
